AWSTemplateFormatVersion: "2010-09-09"

Description: Cruddur AWS Cognito CFN

Parameters:
  UserPoolName:
    Type: String
    MinLength: 3
    MaxLength: 128
    AllowedPattern: '[\w\s+=,.@-]+'
    Description: Enter a string. Must be alpha numeric 3-128 in length.
  CognitoDomain:
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$
    Description: Enter a string. Must be alpha numeric 3-63 in length.  
  CognitoEmail:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
    Default: no-reply@verificationemail.com
    Description: Enter an email that have been verified with Amazon SES.
  CallbackURLs:
    Type: List<String>
    Description: Enter at least one callback URL to redirect the user back to after authentication. For example, https://localhost:80/callback
  ClientName:
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '[\w\s+=,.@-]+'
    Description: Enter a string. Must be alpha numeric 3-128 in length.

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      MfaConfiguration: OPTIONAL
      EnabledMfas : 
        - SOFTWARE_TOKEN_MFA 
      AccountRecoverySetting: 
        RecoveryMechanisms: 
        -   Name: verified_email
            Priority: 2
      UsernameConfiguration: 
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      UserPoolName: !Sub ${UserPoolName}

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: true
      ClientName: !Ref ClientName
      CallbackURLs: !Ref CallbackURLs
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomain
      UserPoolId: !Ref UserPool

Outputs:
  UserPoolUD:
    Value: !Ref UserPool
    Description: UserPoolID
  UserPoolClientID:
    Value: !Ref UserPoolClient
    Description: UserPoolClientID